<?php
    $this->layout('layout/layoutlogin');
    $title = 'Login';
    $this->headTitle($title);
?>
<h1 class="d-flex justify-content-center"><?= $this->escapeHtml($title) ?></h1>
<?php

    $username = $form->get('username');
    $username->setAttribute('class', 'form-control');
    $username->setAttribute('placeholder', 'Username');

    $password = $form->get('password');
    $password->setAttribute('class', 'form-control');
    $password->setAttribute('placeholder', 'Password');

    // This provides CSS classes for the submit button:
    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-primary mr-2');

    $form->setAttribute('action', $this->url('login', ['action' => 'index']));

    $form->prepare();

    echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($username) ?>
    <?= $this->formElement($username) ?>
    <?= $this->formElementErrors()->render($username, ['class' => 'help-block']) ?>
    <?= $this->formLabel($password) ?>
    <?= $this->formElement($password) ?>
    <?= $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
</div>

<?php
    echo $this->formSubmit($submit);
    echo $this->form()->closeTag();
?>