
<?php
    $this->layout('layout/layoutmodaldelete');
?>
<!-- Modal -->
<form action="<?= $url ?>" method="post">
    <div class="modal fade" id="modalExemplo" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Exclusão</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Confirma a ação?
            </div>
            <div class="modal-footer">
                <input type="submit" class="btn btn-danger" name="del" value="Sim" />
                <input type="submit" class="btn btn-success" name="del" value="Não" />
            </div>
            </div>
        </div>
    </div>
</form>