<?php
    $title = 'Adicionar novo contato';
    $this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
    $contato = $form->get('contato');
    $contato->setAttribute('class', 'form-control');
    $contato->setAttribute('placeholder', 'contato');

    $id_pessoa = $form->get('id_pessoa');
    $id_pessoa->setAttribute('class', 'form-control');

    /*$id_pessoa->setValueOptions([
        '1' => 'Adele',
    ]);*/

    // This provides CSS classes for the submit button:
    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-primary');

    $form->setAttribute('action', $this->url('contato', ['action' => 'add']));
    $form->prepare();

    echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group w-50 p-3 border bg-light">
    <?= $this->formLabel($contato) ?>
    <?= $this->formElement($contato) ?>
    <?= $this->formElementErrors()->render($contato, ['class' => 'help-block']) ?>
    <?= $this->formLabel($id_pessoa) ?>
    <?= $this->formElement($id_pessoa) ?>
    <?= $this->formElementErrors()->render($id_pessoa, ['class' => 'help-block']) ?>
</div>

<?php
    echo $this->formSubmit($submit);
    echo $this->formHidden($form->get('id'));
    echo $this->form()->closeTag();
?>
<a href="<?= $this->url('contato', ['action' => 'index']) ?>" class="btn btn-primary mt-5">Voltar para Pesquisa</a>