<?php
    $title = 'Adicionar novo contato';
    $this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<?= $this->inlineScript()
    ->prependFile($this->basePath('js/dist/jquery.inputmask.min.js'))
    ->prependFile($this->basePath('js/contato/maskcontato.js'))
?>

<?php
    $contato = $form->get('contato');
    $contato->setAttribute('class', 'form-control');
    $contato->setAttribute('placeholder', 'contato');
    $contato->setAttribute('id', 'tel');

    $id_pessoa = $form->get('id_pessoa');
    $id_pessoa->setAttribute('class', 'form-control');

    /*$id_pessoa->setValueOptions([
        '1' => 'Adele',
    ]);*/

    // This provides CSS classes for the submit button:
    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-primary');

    $form->setAttribute('action', $this->url('contato', ['action' => 'add']));
    $form->prepare();

    echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<form>      
    <div class="form-row">
        <div class="form-group col-md-3">
            <?= $this->formLabel($contato) ?>
            <?= $this->formElement($contato) ?>
            <?= $this->formElementErrors()->render($contato, ['class' => 'help-block']) ?>
        </div>
        <div class="form-group col-md-3">
            <?= $this->formLabel($id_pessoa) ?>
            <?= $this->formElement($id_pessoa) ?>
            <?= $this->formElementErrors()->render($id_pessoa, ['class' => 'help-block']) ?>
        </div>
    </div>

    <div class="form-row border bg-light">
        <div class="form-group col-md-1 mt-3 mr-2">
            <?= $this->formSubmit($submit); ?>
            <?= $this->formHidden($form->get('id')); ?>
            <?= $this->form()->closeTag(); ?>
        </div>
        <div class="form-group col-md-1">
            <a href="<?= $this->url('contato', ['action' => 'index']) ?>" class="btn btn-primary mt-3">Voltar para Pesquisa</a>
        </div>
    </div>
</form>