<?php
// module/Album/view/pessoa/pessoa/add.phtml:
$this->layout('layout/layoutagenda/layoutpessoa');
$title = 'Dados do Contato';
$this->headTitle($title);
?>

<?= $this->inlineScript()
    ->prependFile($this->basePath('js/dist/jquery.inputmask.min.js'))
    ->prependFile($this->basePath('js/contato/maskcontato.js'))
?>

<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$url = $this->url('contato', ['action' => 'delete', 'id' => $id]);

$contato = $form->get('contato');
$contato->setAttribute('class', 'form-control  col ml-2');
$contato->setAttribute('placeholder', 'contato');
$contato->setAttribute('id', 'tel');

$id_pessoa = $form->get('id_pessoa');
$id_pessoa->setAttribute('class', 'form-control col ml-2');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

// Componente dialog para confirmação de ações
$dialogdeletar = $form->get('dialogdeletar');
$dialogdeletar->setAttribute('class', 'btn btn-primary');
$dialogdeletar->setAttribute('data-toggle', 'modal');
$dialogdeletar->setAttribute('data-target', '#modalExemplo');

$form->setAttribute('action', $this->url('contato', [
                    'action' => 'editdelete',
                    'id' => $id,
]));

$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>

<form>      
    <div class="form-row">
        <div class="form-group col-md-3">
            <?= $this->formLabel($contato) ?>
            <?= $this->formElement($contato) ?>
            <?= $this->formElementErrors()->render($contato, ['class' => 'help-block']) ?>
        </div>
        <div class="form-group col-md-3">
            <?= $this->formLabel($id_pessoa) ?>
            <?= $this->formElement($id_pessoa) ?>
            <?= $this->formElementErrors()->render($id_pessoa, ['class' => 'help-block']) ?>
        </div>
    </div>

    <div class="form-row border bg-light">
        <div class="form-group col-md-0 mt-3">
            <?= $this->formSubmit($submit); ?>
            <?= $this->formHidden($form->get('id')); ?>
        </div>
        <div class="form-group col-md-0 mt-3">
            <?= $this->formButton($dialogdeletar, 'Deletar'); ?>
            <?= $this->form()->closeTag(); ?>
        </div>
        <div class="form-group col-md-1">
            <a href="<?= $this->url('contato', ['action' => 'index']) ?>" class="btn btn-primary mt-3">Voltar para Pesquisa</a>
        </div>
    </div>
</form>    

<?php
    // Modal de exclusão de arquivo
    //include __DIR__ . '/../layout/layoutagenda/modaldelete.phtml';
    //include __DIR__ . '/../../window/modaldelete.phtml';
    include 'module/Application/view/window/modaldelete.phtml'
?>


