<?php
    // module/Album/view/pessoa/pessoa/add.phtml:
    $this->layout('layout/layout');
    $title = 'Adicionar nova pessoa';
    $this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<?= $this->inlineScript()
    ->prependFile($this->basePath('js/dist/jquery.inputmask.min.js'))
    ->prependFile($this->basePath('js/pessoa/maskpessoa.js'))
?>

<?php
    $nome = $form->get('nome');
    $nome->setAttribute('class', 'form-control');
    $nome->setAttribute('placeholder', 'Nome');
    //$nome->setAttribute('onselect', 'myFunction()');
    

    $tipo = $form->get('tipo');
    $tipo->setAttribute('class', 'form-control');
    $tipo->setAttribute('id', 'tipo');

    $rg = $form->get('rg');
    $rg->setAttribute('class', 'form-control');
    $rg->setAttribute('placeholder', '99.999.999-9');
    $rg->setAttribute('id', 'rg');

    $cpfcnpj = $form->get('cpfcnpj');
    $cpfcnpj->setAttribute('class', 'form-control');
    $cpfcnpj->setAttribute('placeholder', '999.999.999-99');
    $cpfcnpj->setAttribute('id', 'cpfcnpj');

    $datanasc = $form->get('datanascimento');
    $datanasc->setAttribute('class', 'form-control');
    $datanasc->setAttribute('placeholder', 'Data Nascimento');
    
    $localnasc = $form->get('localnascimento');
    $localnasc->setAttribute('class', 'form-control');
    $localnasc->setAttribute('placeholder', 'Local Nascimento');

    $estadonasc = $form->get('estadonascimento');
    $estadonasc->setAttribute('class', 'form-control');
    $estadonasc->setAttribute('placeholder', 'Estado Nascimento');

    // This provides CSS classes for the submit button:
    $submit = $form->get('submit');
    $submit->setAttribute('class', 'btn btn-primary');

    $form->setAttribute('action', $this->url('pessoa', ['action' => 'add']));
    $form->prepare();

    echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<form>
    <div class="form-row">
        <div class="form-group col-md-6">
            <?= $this->formLabel($nome) ?>
            <?= $this->formElement($nome) ?>
            <?= $this->formElementErrors()->render($nome, ['class' => 'small text-danger']) ?>
        </div>    
        <div class="form-group col-md-3">
            <?= $this->formLabel($tipo) ?>
            <?= $this->formElement($tipo) ?>
            <?= $this->formElementErrors()->render($tipo, ['class' => 'small text-danger']) ?>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-2">
            <?= $this->formLabel($rg) ?>
            <?= $this->formElement($rg) ?>
            <?= $this->formElementErrors()->render($rg, ['class' => 'help-block']) ?>
        </div>
        <div class="form-group col-md-2">
            <?= $this->formLabel($cpfcnpj) ?>
            <?= $this->formElement($cpfcnpj) ?>
            <?= $this->formElementErrors()->render($cpfcnpj, ['class' => 'help-block']) ?>
        </div>
        <div class="form-group col-md-2">
            <?= $this->formLabel($datanasc) ?>
            <?= $this->formElement($datanasc) ?>
            <?= $this->formElementErrors()->render($datanasc, ['class' => 'help-block']) ?>
        </div>
        <div class="form-group col-md-6">
            <?= $this->formLabel($localnasc) ?>
            <?= $this->formElement($localnasc) ?>
            <?= $this->formElementErrors()->render($localnasc, ['class' => 'help-block']) ?>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-2">
            <?= $this->formLabel($estadonasc) ?>
            <?= $this->formElement($estadonasc) ?>
            <?= $this->formElementErrors()->render($estadonasc, ['class' => 'help-block']) ?>
        </div>
    </div>

    <div class="form-row border bg-light">
        <div class="form-group col-md-1 mt-3 mr-2">
            <?= $this->formSubmit($submit) ?>
            <?= $this->formHidden($form->get('id')) ?>
            <?= $this->form()->closeTag() ?>
        </div>
        <div class="form-group col-md-1">
            <a href="<?= $this->url('pessoa', ['action' => 'index']) ?>" class="btn btn-primary mt-3">Voltar para Pesquisa</a>
        </div>
    </div>
</form>

<?php 
    // Footer
    //$this->layout()->setVariable('infoText', '<a href=' . $this->url('pessoa', ['action' => 'add']) . ' class="nav-link px-2 text-muted">Voltar</a>');
?>