<?php
// module/Album/view/pessoa/pessoa/add.phtml:
$this->layout('layout/layoutagenda/layoutpessoa');
$title = 'Dados da Pessoa';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$url = $this->url('pessoa', ['action' => 'delete', 'id' => $id]);

$nome = $form->get('nome');
$nome->setAttribute('class', 'form-control');
$nome->setAttribute('placeholder', 'Nome');
//$nome->setAttribute('disabled', true);

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary mr-2');

$form->setAttribute('action', $this->url('pessoa', [
                    'action' => 'editdelete',
                    'id' => $id,
]));

// Componente dialog para confirmação de ações
$dialogdeletar = $form->get('dialogdeletar');
$dialogdeletar->setAttribute('class', 'btn btn-primary mr-2');
$dialogdeletar->setAttribute('data-toggle', 'modal');
$dialogdeletar->setAttribute('data-target', '#modalExemplo');

$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group w-50 p-3 border bg-light">
    <?= $this->formLabel($nome) ?>
    <?= $this->formElement($nome) ?>
    <?= $this->formElementErrors()->render($nome, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formButton($dialogdeletar, 'Deletar');
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
<p>
    <a href="<?= $this->url('pessoa', ['action' => 'index']) ?>" class="btn btn-primary mt-5">Voltar para Pesquisa</a>
</p>    


<?php
    // Modal de exclusão de arquivo
    //include __DIR__ . '/../layout/layoutagenda/modaldelete.phtml';
    include 'module/Application/view/window/modaldelete.phtml';
?>

<?php 
    // Footer
    //$this->layout()->setVariable('infoText', '<a href=' . $this->url('pessoa', ['action' => 'add']) . ' class="nav-link px-2 text-muted">Voltar</a>');
?> 