<?php
    $this->layout('layout/layoutagenda/layoutpessoa');

    $title = 'Agenda';
    $this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('pessoa', ['action' => 'add']) ?>" class="btn btn-primary mt-5">Adicionar nova pessoa</a>
</p>
<p>
    <?php include __DIR__ . '/../../filter/filteragenda/filtroordenar.phtml'; ?>
</p>
    <table class="table table-hover">
        <thead>
            <tr class="border bg-light">
                <th scope="col">Id </th>
                <th scope="col">Nome</th>
            </tr>
        </thead>    
        <?php foreach ($paginator as $pessoa) : ?>
            <tbody>
                <tr class="tabelahover" onclick="window.location='<?= $this->url('pessoa', ['action' => 'editdelete', 'id' => $pessoa->id]) ?>'">
                    <td><?= $this->escapeHtml($pessoa->id) ?></td>
                    <td><?= $this->escapeHtml($pessoa->nome) ?></td>
                </tr>
            </tbody>
        <?php endforeach; ?>
    </table>
    <?= $this->paginationControl(
        // The paginator object:
        $this->paginator,
        // The scrolling style:
        'sliding',
        // The partial to use to render the control:
        'partial/paginator',
        // The route to link to when a user clicks a control link:
        ['route' => 'pessoa']
    ) ?>

<?php   
  // Footer
  $this->layout()->setVariable('infoText', '<a href="' . $this->url('login', ['action' => 'index']) . '" class="nav-link px-2 text-muted">Logout</a>');
?>    


