<?php

$this->layout('layout/layoutagenda/layoutpessoa');

$title = 'Agenda';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('pessoa', ['action' => 'add']) ?>" class="btn btn-primary mt-5">Adicionar nova pessoa</a>
</p>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nome</th>
                <th scope="col">#</th>
            </tr>
        </thead>    
        <?php foreach ($pessoas as $pessoa) : ?>
            <tbody>
                <tr>
                    <td><?= $this->escapeHtml($pessoa->id) ?></td>
                    <td><?= $this->escapeHtml($pessoa->nome) ?></td>
                    <td>
                        <a href="<?= $this->url('pessoa', ['action' => 'edit', 'id' => $pessoa->id]) ?>" class="btn btn-primary">Editar</a>
                        <a href="<?= $this->url('pessoa', ['action' => 'delete', 'id' => $pessoa->id]) ?>" class="btn btn-primary">Deletar</a>
                    </td>
                </tr>
            </tbody>
        <?php endforeach; ?>
    </table>
