<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Laminas MVC')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
    ?>
</head>
<body>
    <header></header>
    <section>
        <div class="container">
            <div class="container d-flex justify-content-center">
                <div class="w-25 p-3 border bg-light">
                    <?= $this->content ?>
                </div>
            </div>
        </div>
    </section>    

    <div class="container w-100">        
        <footer class="py-3 my-4 w-100 p-3">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item">
                <?php if (isset($infoText)){
                        echo $infoText;
                      }
                ?> 
                </li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
            </ul>
            <p class="text-center text-muted">© Feito pelo Maicon 2022</p>
        </footer>
    </div>
</body>
</html>