<ul class="nav flex-column">
  <li class="nav-item">
    <a class="nav-link btn btn-primary mb-2" href="<?= $this->url('pessoa', ['action' => 'index']) ?>">Pessoa</a>
  </li>
  <li class="nav-item">
    <a class="nav-link btn btn-primary mb-2" href="<?= $this->url('contato', ['action' => 'index']) ?>">Contato</a>
  </li>
</ul>
<?php   
  // Footer
  $this->layout()->setVariable('infoText', '<a href="' . $this->url('login', ['action' => 'index']) . '" class="nav-link px-2 text-muted">Logout</a>');
?>