<?php
  $this->layout('layout/layoutmain');
?>

<nav class="navbar navbar-expand-lg navbar-light bg-light border fixed-top">
  <span class="navbar-brand">Agenda</span>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Pesquisas
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item btn btn-primary mb-2" href="<?= $this->url('pessoa', ['action' => 'index']) ?>">Pessoa</a>
          <a class="dropdown-item btn btn-primary mb-2" href="<?= $this->url('contato', ['action' => 'index']) ?>">Contato</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

<?php   
  // Footer
  $this->layout()->setVariable('infoText', '<a href="' . $this->url('login', ['action' => 'index']) . '" class="nav-link px-2 text-muted">Logout</a>');
?>